website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func
from sqlalchemy import Boolean
from sqlalchemy import Date

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())


    habits = db.relationship('Habit', backref='user', lazy=True)

class Habit(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    consecutive_days = db.Column(db.Integer, default=0)
    completed = db.Column(Boolean, default=False)
    day_of_fulfillment = db.Column(Date)


    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "helloworld"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists("website/" + DB_NAME):
        with app.app_context():  # Dies stellt sicher, dass die Anwendungskontext aktiv ist
            db.create_all()
        print("Created database!")

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import db
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in!", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get("email")
        username = request.form.get("username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()

        if email_exists:
            flash('Email is already in use.', category='error')
        elif username_exists:
            flash('Username is already in use.', category='error')
        elif password1 != password2:
            flash('Password don\'t match!', category='error')
        elif len(username) < 2:
            flash('Username is too short.', category='error')
        elif len(password1) < 6:
            flash('Password is too short.', category='error')
        elif len(email) < 4:
            flash("Email is invalid.", category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('User created!')
            return redirect(url_for('views.home'))

    return render_template("sign-up.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Habit
from . import db
from datetime import datetime, timedelta

views = Blueprint("views", __name__)
today = datetime.now().date()


@views.route("/")
@views.route("/home")
@login_required
def home():
    incompleted_habits = Habit.query.filter(Habit.completed == False, Habit.user_id==current_user.id).all()
    num_habits = len(incompleted_habits)
    return render_template("home.html", user=current_user, num_incomplete_habits = num_habits)


@views.route("/habits", methods=["GET", "POST"])
@login_required
def habits():
    completed_habits = Habit.query.filter(Habit.completed == True).all()
    for x in completed_habits:
        if today == x.day_of_fulfillment:
            pass
        else:
            x.completed = False
    
    if request.method == "POST":
        completed_habits_ids = request.form.getlist("completed")
        for habit_id in completed_habits_ids:
            habit = Habit.query.filter_by(id=habit_id).first()
            if habit:
                habit.completed = True
                if habit.day_of_fulfillment == today - timedelta(days=1):
                    habit.consecutive_days += 1
                else:
                    habit.consecutive_days = 1
                habit.day_of_fulfillment = today
                flash(f"{habit.name} is completed", category="success")
            else:
                flash(f"Habit with ID {habit_id} not found", category="error")

            db.session.commit()
            

    habits = Habit.query.filter(Habit.user_id == current_user.id)
    return render_template("habits.html", user=current_user, habits=habits)


        
@views.route("/add-habit", methods=["GET", "POST"])
@login_required
def add_habit():
    if request.method == "POST":
        name = request.form.get("name")
        user_id = current_user.id

        new_habit = Habit(name=name, consecutive_days=0, user_id=user_id)
        db.session.add(new_habit)
        db.session.commit()
        flash("New Habit created", category="success")
        return redirect(url_for("views.habits"))
    
    return render_template("add-habit.html", user=current_user)



@views.route("/delete-habit/<int:habit_id>")
@login_required
def delete_habit(habit_id):
    habit = Habit.query.get_or_404(habit_id)
    db.session.delete(habit)
    db.session.commit()
    flash("Habit deleted successfully.", "success")
    return redirect(url_for('views.habits'))


@views.route("/change-habit/<int:habit_id>", methods=["GET", "POST"])
@login_required
def change_habit(habit_id):
    habit = Habit.query.get_or_404(habit_id)
    
    if request.method == "POST":
        name = request.form.get("name")
        if current_user.id == habit.user_id:
            habit.name = name
            db.session.commit()
            flash("Habit changed", category="success")
        else:
            flash("You are not allowed to change this habit", "error")
        return redirect(url_for('views.habits'))

    return render_template("change_habit.html", user=current_user, habit=habit)




website/templates/add-habit.html
{% extends "base.html" %} {% block title %}Add Habit{% endblock %} 
{% block content %}
<form method="POST">
    <h3 align="center"> Add habit </h3>
    <div class="form group">
        <input type="text" id="name" name="name" class="form-control" placeholder="Enter habit name"/>
    </div>
</br>
<div align="center">
    <button type="submit" class="btn btn-primary">Add habit</button>
</div>
</form>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="/home">Home</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="/logout">Logout</a>
            <a class="nav-item nav-link" href="/habits">Habits</a>
            {% else %}
            <a class="nav-item nav-link" href="/login">Login</a>
            <a class="nav-item nav-link" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for category, message in messages %}
        {% if category == "error" %}
        <div class="alert alert-danger alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% endif %}

        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="container">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/change_habit.html
{% extends "base.html" %} {% block title %}Change Habit{% endblock %} 
{% block content %}
<form method="POST">
    <h3 align="center"> Change Habit </h3>
    <div class="form group">
        <input type="text" id="name" name="name" class="form-control" placeholder="Enter new habit name"/>
    </div>
</br>
<div align="center">
    <button type="submit" class="btn btn-primary">Change habit</button>
</div>
</form>
{% endblock %}

website/templates/habits.html
{% extends "base.html" %}
{% block title %}Habits{% endblock %}
{% block content %}

</br>
<h3 align="center">Habits</h3>
</br>
<div align="center">
    <button type="button" class="btn btn-primary" onclick="window.location.href='/add-habit'">Add habit</button>
</div>
</br>
<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Date Created</th>
                <th scope="col">Consecutive Days</th>
                <th scope="col">last fulfillment</th>
                <th scope="col">Completed</th>  <!-- Neue Spalte für die Checkbox -->
                <th scope="col">Delete</th>
                <th scope="col">Change</th>
            </tr>
        </thead>
        <tbody>
            {% for habit in habits %}
            {% if habit.completed==False%}
            <tr>
                <td>{{ habit.name }}</td>
                <td>{{ habit.date_created.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                <td>{{ habit.consecutive_days }}</td>
                <td>{{ habit.day_of_fulfillment }}</td>
                <td><input type="checkbox" name="completed" value="{{ habit.id }}"></td>  <!-- Checkbox für jede Gewohnheit -->
                <td>
                    <a href="{{ url_for('views.delete_habit', habit_id=habit.id) }}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this habit?')">Delete</a>
                </td>
                <td>
                    <a href="{{ url_for('views.change_habit', habit_id=habit.id) }}" class="btn btn-warning">Change</a>
                <td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <div align="center">
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</form>
</br>
</br>
    <h3 align="center">Done</h3>
    <br>
    <div align="center"> <!-- Hinzugefügt, um die Tabelle zentriert anzuzeigen -->
        <form method="post">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Date Created</th>
                        <th scope="col">Consecutive Days</th>
                        <th scope="col">last fulfillment</th>
                        <th scope="col">Delete</th>
                        <th scope="col">Change</th>
                    </tr>
                </thead>
                <tbody>
                    {% for habit in habits %}
                    {% if habit.completed==True %}
                    <tr>
                        <td>{{ habit.name }}</td>
                        <td>{{ habit.date_created.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                        <td>{{ habit.consecutive_days }}</td>
                        <td>{{ habit.day_of_fulfillment }}</td>
                        <td><a href="{{ url_for('views.delete_habit', habit_id=habit.id) }}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this habit?')">Delete</a></td>
                        <td>
                            <a href="{{ url_for('views.change_habit', habit_id=habit.id) }}" class="btn btn-warning">Change</a>
                        <td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </form>
    </div> <!-- Hinzugefügt, um die Tabelle zentriert anzuzeigen -->
    
{% endblock %}


website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content %}
<style>
body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
    }
    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        text-align: center;
    }
    h1 {
        color: #333;
    }
    .habits-summary {
        font-size: 24px;
        margin-top: 30px;
        color: #007bff;
    }
</style>
<div class="container">
    <h1>Habits Summary</h1>
    <p class="habits-summary">Incomplete Habits: {{ num_incomplete_habits }}</p>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} 
{% block content %}
<form method="POST">
    <h3 align="center"> Login </h3>
    <div class="form group">
        <label for="email">Email Address</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email"/> 
    </div>

    <label for="password">Password</label>
    <input
      type="password"
      id="password"
      name="password"
      class="form-control"
      placeholder="Enter Password"
    />
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
</form>
{% endblock %}

website/templates/sign-up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="text"
          id="email"
          name="email"
          class="form-control"
          placeholder="Enter Email"
        />
        <label for="username">Username</label>
        <input
          type="text"
          id="username"
          name="username"
          class="form-control"
          placeholder="Enter Username"
        />
        <label for="password1">Password</label>
        <input
          type="password"
          id="password1"
          name="password1"
          class="form-control"
          placeholder="Enter Password"
        />
        <label for="password2">Password Again</label>
        <input
          type="password"
          id="password2"
          name="password2"
          class="form-control"
          placeholder="Enter Password Again"
        />
        <br />
        <div align="center">
          <button class="btn btn-primary" type="submit">Sign Up</button>
        </div>
      </div>
    </form>
    {% endblock %}